
# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - node/test:
          # This is the node version to use for the `cimg/node` tag
          # Relevant tags can be found on the CircleCI Developer Hub
          # https://circleci.com/developer/images/image/cimg/node
          version: '12.17'
          # If you are using yarn, change the line below from "npm" to "yarn"
          pkg-manager: npm





stages:
  - build
  - deploy
 
dev_build:
  stage: build
  variables:
    GIT_CLEAN_FLAGS: none
  script:                
    - git config --global url."https://".insteadOf git://
    - npm install
    - npm run build

  tags:
    - dev-runner
 
  only:
    - master

dev_deploy:
  stage: deploy
  variables:
    GIT_STRATEGY: none

  script:
    - sudo cp -rf dist /home/samefeel/vue-skeleton

  tags:
    - dev-runner
 
  only:
    - master

live_build:
  stage: build
  variables:
    GIT_CLEAN_FLAGS: none
  script:
    - npm run build

  tags: 
    - live-runner
 
  only:
    - tags

live_deploy:
  stage: deploy
  variables:
    GIT_STRATEGY: none

  script:
    - sudo cp -rf dist /usr/share/nginx/vue-skeleton/
    - tar -zcvf dist.tar.gz dist/
    
  tags:
    - live-runner
 
  only:
    - tags
